# Numpy
Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and amtrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will conver the basics of Numy, focusing on arrays and vectorized operations.

In [4]:
import numpy as np
# Create arrays using numpy

# 1D Array
arr1 = np.array([1,2,3,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 3 4 5 6]
<class 'numpy.ndarray'>
(7,)


In [11]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(1,6) # This is 1 row and 5 column

array([[1, 2, 3, 4, 5, 6]])

In [17]:
# 2D Array
arr3 = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]]
(2, 7)


### Inbuilt Array Function

In [20]:
# np.arange = np.arange(0, 10, 2) creates an array starting from 0, up to but not including 10, in steps of 2.
# np.reshape = .reshape(5, 1) changes the shape of the array to 5 rows and 1 column.
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [23]:
# np.ones = The np.ones() function is used to create a new NumPy array filled entirely with 1 values.
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
# Identity matrix
# np.eye() = The np.eye() function is used to create an identity matrix — a square matrix with 1s on the diagonal (from top-left to bottom-right) and 0s elsewhere.

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Attributes of Numpy Array

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# ndim(): Returns the number of dimensions (axes) of the array.
print("Number of dimensions: ",arr.ndim)

# .shape(): Gives a tuple representing the dimensions (rows, columns).
print("Shape of an array: ", arr.shape)

# .size(): Total number of elements in the array.
print("Total elements in array: ", arr.size)

#.dtype(): Shows the data type of array elements.
print("Data type of an array: ",arr.dtype)

# .itemsize(): Tells how much memory (in bytes) one array element uses.
print("Memory size of one element: ",arr.itemsize)

# .nbytes(): Total number of bytes consumed by array
print("Memory consumed by an array: ", arr.nbytes)

Number of dimensions:  2
Shape of an array:  (3, 3)
Total elements in array:  9
Data type of an array:  int64
Memory size of one element:  8
Memory consumed by an array:  72


### Vectorized Operation

In [44]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise operation

# Addition
print("Addition", arr1+arr2)

# Subtraction 
print("Subtraction",arr1-arr2)

# Multiplication
print("Multiplication",arr1*arr2)

# Division 
print("Division",arr1/arr2)

Addition [11 22 33 44 55]
Subtraction [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]
Division [0.1 0.1 0.1 0.1 0.1]


### Universal Function

In [ ]:
arr = np.array([2,3,4,5,6,7,8,9])

# Square root
print("Square Root: ",np.sqrt(arr))

# Exponential
print("Exponential: ",np.exp(arr))

# Sine
print("Sine: ",np.sin(arr))

# natural log
print("Natural Log: ",np.log(arr))

Square Root:  [1.41421356 1.73205081 2.         2.23606798 2.44948974 2.64575131
 2.82842712 3.        ]
Exponential:  [7.38905610e+00 2.00855369e+01 5.45981500e+01 1.48413159e+02
 4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03]
Sine:  [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866
  0.98935825  0.41211849]
Natural Log:  [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015
 2.07944154 2.19722458]


### Slicing operation

Slicing in NumPy is used to extract a portion (subset) of an array using index ranges. It's similar to slicing in Python lists, but works on multi-dimensional arrays too.

In [82]:
arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print(arr)

print("Accessing element 1 we can use 'arr[0][0]' : ", arr[0][0],sep='\n')
print()
print("Accessing element [9,10,11,12] we can use 'arr[2]' : ", arr[2],sep='\n')
print()
print("Accessing element [[[7,8], [11,12]]] we can use 'arr[1:, 2:]' : ", arr[1:, 2:], sep='\n' )
print()
print("Accessing element [[[3,4], [7,8]]] we can use 'arr[0:, 2:]' : ", arr[0:, 2:], sep='\n')
print()
print("Accessing element [[6,7],[10,11]] we can use 'arr[1:,1:3]' : ", arr[1:,1:3], sep='\n')
print()
print()
print("Reversing an array: ", arr[::-1],sep='\n')
arr[0][0]=100
print("Modifying an element 1 to 100 we can use 'arr[0][0] = 100' :", arr, sep='\n')
print()
arr[1:] = 100



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Accessing element 1 we can use 'arr[0][0]' : 
1

Accessing element [9,10,11,12] we can use 'arr[2]' : 
[ 9 10 11 12]

Accessing element [[[7,8], [11,12]]] we can use 'arr[1:, 2:]' : 
[[ 7  8]
 [11 12]]

Accessing element [[[3,4], [7,8]]] we can use 'arr[0:, 2:]' : 
[[ 3  4]
 [ 7  8]
 [11 12]]

Accessing element [[6,7],[10,11]] we can use 'arr[1:,1:3]' : 
[[ 6  7]
 [10 11]]


Reversing an array: 
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Modifying an element 1 to 100 we can use 'arr[0][0] = 100' :
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]



### 1. Basic Descriptive Statistics Using Numpy

In [87]:
data = np.array([1,2,3,4,5])
mean = np.mean(data)
print("The mean is: ",mean)
print()

median = np.median(data)
print("The median is: ",median)
print()

variance = np.var(data)
print("The vairance is: ",variance)
print()

min = np.min(data)
max = np.max(data)
data_range = np.ptp(data)
print("The minimum value is: ",min)
print("The maximum value is: ",max)
print("The range of data is (5-1): ",data_range)
print()

q1 = np.percentile(data,25)
q2 = np.percentile(data,75)
print("The 1st quartile in data is: ",q1)
print("The 2nd quartile in data is: ",q2)
print()

The mean is:  3.0

The median is:  3.0

The vairance is:  2.0

The minimum value is:  1
The maximum value is:  5
The range of data is (5-1):  4

The 1st quartile in data is:  2.0
The 2nd quartile in data is:  4.0



### Correlation & Covariance


In [88]:
x = np.array([1,2,3,4,5])
y = np.array([5,4,3,2,1])
cov_matrix = np.cov(x,y)
print(cov_matrix)

[[ 2.5 -2.5]
 [-2.5  2.5]]


In [90]:
corr = np.corrcoef(x, y)[0, 1]  # Returns a correlation matrix
print(corr)

-0.9999999999999999


### Distributions & Random Sampling

In [96]:
uniform_samples = np.random.uniform(low=0,high=1, size=10)
print('Uniform Distribution')
print(uniform_samples)

Uniform Distribution
[0.31330554 0.38748589 0.73541803 0.94072765 0.26938633 0.98573843
 0.58786365 0.07527673 0.32210443 0.98647412]


In [98]:
normal_samples = np.random.normal(loc=0,scale=1,size=10)
print('Normal Distribution')
print(normal_samples)

Normal Distribution
[-6.99414748e-01  4.75574688e-02 -7.26944633e-01 -2.02941327e+00
 -1.80230227e+00  4.30602225e-01  6.70775795e-01  2.52473522e-04
 -1.42866910e+00 -4.31076712e-01]


In [100]:
binomial_samples = np.random.binomial(10,0.5,10)
print('Binomial Distribution')
print(binomial_samples)

Binomial Distribution
[3 6 8 2 5 6 5 4 6 7]


In [102]:
data = np.random.randn(1000)
counts,bins = np.histogram(data,bins=10)
print(counts,bins)

[  1   6  35 102 215 272 230 103  26  10] [-3.84610256 -3.14693205 -2.44776154 -1.74859103 -1.04942053 -0.35025002
  0.34892049  1.048091    1.7472615   2.44643201  3.14560252]
