# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [15]:
import numpy as np
arr = np.random.randint(1,21,size=(5,5))
print("Orrignal Array: ",arr,sep="\n")
arr[:,3] = 1
print()
print("Updated Array: ",arr,sep="\n")

Orrignal Array: 
[[ 5 15 20  9 20]
 [ 8 15  2  4 18]
 [ 5 19 14  5 14]
 [ 2 13  7  8 18]
 [ 3 16  1  5 10]]

Updated Array: 
[[ 5 15 20  1 20]
 [ 8 15  2  1 18]
 [ 5 19 14  1 14]
 [ 2 13  7  1 18]
 [ 3 16  1  1 10]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [24]:
arr = np.random.randint(1,17,size=(4,4))
print('Original Array: ',arr,sep='\n')
print()
np.fill_diagonal(arr,0)
print('Updated Array: ',arr,sep='\n')

Original Array: 
[[13  3  5  3]
 [13 12  1  7]
 [ 9  9  1  5]
 [ 3 16  8  2]]

Updated Array: 
[[ 0  3  5  3]
 [13  0  1  7]
 [ 9  9  0  5]
 [ 3 16  8  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


In [31]:
arr = np.random.randint(1,37,size=(6,6))
print("Original Array:",arr,sep='\n')
print()
print("Sub-Array: ",arr[2:5,2:5],sep='\n')

Original Array:
[[11  7  4 14 22 25]
 [ 1 14  9  2 17 24]
 [28 34 33 32 27 33]
 [ 4 32  9 14  4 29]
 [ 2 19 11 31 20 18]
 [10  6  4 14 21 22]]

Sub-Array: 
[[33 32 27]
 [ 9 14  4]
 [11 31 20]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [41]:
arr = np.random.randint(1,10,size=(5,5))
print('Original Array: ',arr,sep='\n')
print()
print("Border elements: ",np.concatenate([arr[0], arr[-1], arr[1:-1,-1], arr[1:-1,0]]), sep='\n')

Original Array: 
[[9 9 8 2 8]
 [3 9 7 6 7]
 [4 7 5 8 8]
 [9 6 6 3 5]
 [3 2 9 5 4]]

Border elements: 
[9 9 8 2 8 3 2 9 5 4 7 8 5 3 4 9]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [42]:
arr1 = np.random.randint(1,10,size=(3,4))
arr2 = np.random.randint(1,10,size=(3,4))
print("Addition: ",arr1+arr2, sep='\n')
print("Subtraction: ",arr1-arr2, sep='\n')
print("Multiplication: ",arr1*arr2, sep='\n')
print("Divinsion: ",arr1/arr2, sep='\n')


Addition: 
[[ 4  8 11 12]
 [10 10  9  8]
 [11  7  4 11]]
Subtraction: 
[[ 2  0 -7 -6]
 [-6 -6 -1  6]
 [ 3  5 -2  7]]
Multiplication: 
[[ 3 16 18 27]
 [16 16 20  7]
 [28  6  3 18]]
Divinsion: 
[[3.         1.         0.22222222 0.33333333]
 [0.25       0.25       0.8        7.        ]
 [1.75       6.         0.33333333 4.5       ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [43]:
arr = np.random.randint(1,16,size=(4,4))
row_sum = np.sum(arr,axis=0)
col_sum = np.sum(arr,axis=1)
print("Row wise sum: ", row_sum, sep='\n')
print("Col wise sum: ", col_sum, sep='\n')

Row wise sum: 
[35 30 37 33]
Col wise sum: 
[44 36 23 32]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [48]:
arr = np.random.randint(1,20,size=(5,5))
print(arr)

print("Mean of an array is: ",np.mean(arr,axis=0), sep='\n')
print()
print("Median of an array is: ",np.median(arr,axis=0), sep='\n')
print()
print("Variance of an array is: ",np.var(arr,axis=0), sep='\n')
print()
print("Std Dev of an array is: ",np.std(arr,axis=0), sep='\n')

[[ 7 14  4 17  7]
 [ 8 16  5 14  6]
 [ 7  6 10  6 19]
 [11  1  6 12 19]
 [17 15 17  5  7]]
Mean of an array is: 
[10.  10.4  8.4 10.8 11.6]

Median of an array is: 
[ 8. 14.  6. 12.  7.]

Variance of an array is: 
[14.4  34.64 22.64 21.36 36.64]

Std Dev of an array is: 
[3.79473319 5.88557559 4.7581509  4.621688   6.05309838]


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [60]:
arr = np.arange(1,10).reshape(3,3)
mean = np.mean(arr,axis=0)
std = np.std(arr,axis=0)

normalize_arr = (arr - mean)/ std
normalize_arr

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [70]:
arr1 = np.random.randint(1,10,size=(3,3))
arr2 = np.random.randint(1,10,size=(3,))
print("Original Array: ",arr1, sep='\n')
print()
print("1D Array: ",arr2, sep='\n')
print()
new_arr = arr1 + arr2
print("Resulting array: ", new_arr,sep='\n')


Original Array: 
[[4 4 1]
 [7 6 7]
 [5 9 3]]

1D Array: 
[9 7 7]

Resulting array: 
[[13 11  8]
 [16 13 14]
 [14 16 10]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [71]:
arr1 = np.random.randint(1,10,size=(4,4))
arr2 = np.random.randint(1,10,size=(4,))
print("Original Array: ",arr1, sep='\n')
print()
print("1D Array: ",arr2, sep='\n')
print()
new_arr = arr1 - arr2
print("Resulting array: ", new_arr,sep='\n')


Original Array: 
[[9 8 4 2]
 [1 5 2 2]
 [3 2 8 8]
 [1 1 3 4]]

1D Array: 
[2 6 5 8]

Resulting array: 
[[ 7  2 -1 -6]
 [-1 -1 -3 -6]
 [ 1 -4  3  0]
 [-1 -5 -2 -4]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [80]:
arr = np.random.randint(1,10,size=(3,3))
print("Original Array: ",arr,sep='\n')
print()
print("Determinant of an array is: ", np.linalg.det(arr), sep='\n')
print()
print("Inverse of an array is: ", np.linalg.inv(arr), sep='\n')
print()
print("Eigenvalues of an array is: ", np.linalg.eigvals(arr), sep='\n')

Original Array: 
[[6 5 6]
 [8 5 9]
 [9 3 9]]

Determinant of an array is: 
27.0

Inverse of an array is: 
[[ 0.66666667 -1.          0.55555556]
 [ 0.33333333  0.         -0.22222222]
 [-0.77777778  1.         -0.37037037]]

Eigenvalues of an array is: 
[19.66297775+0.j          0.16851113+1.15963051j  0.16851113-1.15963051j]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [83]:
arr1 = np.random.randint(1,10,size=(2,3))
arr2 = np.random.randint(1,10,size=(3,2))
print("Original Array 1: ", arr1, sep='\n')
print()
print("Original Array 2: ", arr2, sep='\n')
print()
print(np.dot(arr1,arr2))
print(np.dot(arr2,arr1))

Original Array 1: 
[[4 9 2]
 [8 8 4]]

Original Array 2: 
[[5 5]
 [9 7]
 [4 9]]

[[109 101]
 [128 132]]
[[ 60  85  30]
 [ 92 137  46]
 [ 88 108  44]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [84]:
arr = np.random.randint(1,9,size=(3,3))
print("Original Array: ",arr,sep='\n')
print()
new_arr = arr.reshape(1,9)
print("New Array with shape (1,9)", new_arr, sep='\n')
print()
new_arr = new_arr.reshape(9,1)
print("New Array with shape (9,1)", new_arr, sep='\n')
print()


Original Array: 
[[4 2 6]
 [1 2 4]
 [8 6 6]]

New Array with shape (1,9)
[[4 2 6 1 2 4 8 6 6]]

New Array with shape (9,1)
[[4]
 [2]
 [6]
 [1]
 [2]
 [4]
 [8]
 [6]
 [6]]



2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [90]:
arr = np.random.randint(1,10,size=(5,5))
print("Original Array: ",arr, sep='\n')
print()
flatten_arr = arr.flatten()
print("Flatten Array: ",flatten_arr,sep='\n')
print()
new_arr = flatten_arr.reshape(5,5)
print("Reshaped Array of size (5,5): ",new_arr,sep='\n')
print()

Original Array: 
[[1 9 4 2 8]
 [4 4 5 3 8]
 [7 4 8 2 9]
 [9 2 6 1 3]
 [2 3 2 2 4]]

Flatten Array: 
[1 9 4 2 8 4 4 5 3 8 7 4 8 2 9 9 2 6 1 3 2 3 2 2 4]

Reshaped Array of size (5,5): 
[[1 9 4 2 8]
 [4 4 5 3 8]
 [7 4 8 2 9]
 [9 2 6 1 3]
 [2 3 2 2 4]]



### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [96]:
arr = np.random.randint(1,10,size=(5,5))
print("Original Array: ",arr,sep='\n') 
print()
corners = arr[[0,0,-1,-1],[0,-1,0,-1]]
print("Corners of an array: ",corners, sep='\n')

Original Array: 
[[9 3 6 2 4]
 [1 2 1 4 5]
 [7 3 2 1 8]
 [9 6 5 8 3]
 [6 9 5 5 4]]

Corners of an array: 
[9 4 6 4]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [104]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

# Use boolean indexing to set all elements greater than 10 to 10
array[array > 10] = 10
print("Modified array:")
print(array)

Original array:
[[ 5 13  1 18]
 [19  5 16 13]
 [16  8 16 17]
 [16  7 20 19]]
Modified array:
[[ 5 10  1 10]
 [10  5 10 10]
 [10  8 10 10]
 [10  7 10 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [ ]:
data_type = [('name','U10')]
arr = np.array()

In [108]:
data_type = [('name','U10'),('age','i4'),('weight','f4')]
data = [
    ("Alice", 25, 55.5),
    ("Bob", 30, 75.2),
    ("Charlie", 20, 68.1),
    ("Diana", 20, 69)
]

people = np.array(data,data_type)
print("Original Array: ",people,sep='\n')
print()
sorted_age = np.sort(people,order='age')
print("Sorted Array: ",sorted_age,sep='\n')

Original Array: 
[('Alice', 25, 55.5) ('Bob', 30, 75.2) ('Charlie', 20, 68.1)
 ('Diana', 20, 69. )]

Sorted Array: 
[('Charlie', 20, 68.1) ('Diana', 20, 69. ) ('Alice', 25, 55.5)
 ('Bob', 30, 75.2)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [109]:
data_type = [('x','i4'),('y','i4')]
data = np.array([(1,2),(3,4),(5,6)], dtype=data_type)
print("Original Array: ", data, sep='\n')

distances = np.sqrt((data['x'][:,np.newaxis]-data['x'])**2 + (data['y'][:,np.newaxis]-data['y'])**2)
print('Euclidean Distance: ',distances, sep='\n')
print()

Original Array: 
[(1, 2) (3, 4) (5, 6)]
Euclidean Distance: 
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]



### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [115]:
arr = np.random.randint(1,21,size=(4,4))
masked_array = np.ma.masked_greater(arr,10)
print("Original Array: ", arr, sep='\n')
print()
print('Masked Array: ',masked_array,sep='\n')

sum_unmasked = masked_array.sum()
print("Sum of unmasked Elements: ", sum_unmasked)

Original Array: 
[[ 8  2 16  4]
 [10 16 13 14]
 [19 18 14  4]
 [ 2 17 14 15]]

Masked Array: 
[[8 2 -- 4]
 [10 -- -- --]
 [-- -- -- 4]
 [2 -- -- --]]
Sum of unmasked Elements:  30


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [127]:
arr = np.random.randint(1,21,size=(3,3))
masked_array = np.ma.masked_array(arr,mask=np.eye(3,dtype=bool))
print('Original Array: ',arr,sep='\n')
print()
print('Masked Array: ',masked_array,sep='\n')
print()
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print('Modified masked array: ', masked_array, sep='\n')

Original Array: 
[[ 3 11 14]
 [15 20  3]
 [19 18 11]]

Masked Array: 
[[-- 11 14]
 [15 -- 3]
 [19 18 --]]

Modified masked array: 
[[13 11 14]
 [15 13  3]
 [19 18 13]]


In [133]:
mean_unmasked

np.float64(13.333333333333334)